server {
    listen 80;
    
    resolver 127.0.0.11 valid=30s;

    location / {
        set $upstream_frontend frontend;
        proxy_pass http://$upstream_frontend:3000;
    }

    location /api/auth {
        set $upstream_auth auth_service;
        proxy_pass http://$upstream_auth:5000;
    }

    location /api/chat {
        set $upstream_chat chat_service;
        proxy_pass http://$upstream_chat:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }

    location /ws {
        set $upstream_front_ws frontend;
        proxy_pass http://$upstream_front_ws:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }
}